---
title: "Balance_Tables"
author: "Kateri Mouawad"
date: "2025-01-03"
output: html_document
---

#START HERE - load packages

```{r}

#remotes::install_github("kwb-r/kwb.utils")

#options(repos = c(
#  kwbr = 'https://kwb-r.r-universe.dev',
#  CRAN = 'https://cloud.r-project.org'))
  
# Download and install kwb.utils in R
#install.packages('kwb.utils')




# install.packages(officer)
# install.packages(r2rtf)
# install.packages(dplyr)
# install.packages(ggplot2)
# install.packages(kwb.utils)
# install.packages(haven)
# install.packages(data.table)
# install.packages(rtf)
# install.packages(tidyverse)
# install.packages(estimatr)
# install.packages(broom)
#install.packages(reshape2)
#library(reshape2)
library(officer)
library(r2rtf)
library(dplyr)
library(ggplot2)
library(kwb.utils)
library(haven)
library(data.table)
library(rtf)
library(tidyverse)
library(estimatr)
library(broom)

```



#File and Data paths
```{r}

# Define the file paths
proj_paths <- list(
  projects = "C:/Users/Kateri/Box/NSF Senegal",
  alternative_projects = "C:/Users/km978/Box/NSF Senegal"
)

# Check if the Kateri path exists and resolve the project path accordingly
if (file.exists(proj_paths$projects)) {
  proj <- kwb.utils::resolve(list(
    projects = proj_paths$projects,
    p1 = "<projects>/Data Management/_CRDES_CleanData/Baseline/Deidentified"
  ))
} else {
  proj <- kwb.utils::resolve(list(
    projects = proj_paths$alternative_projects,
    p1 = "<projects>/Data Management/_CRDES_CleanData/Baseline/Deidentified"
  ))
}



# proj <- kwb.utils::resolve(list(
#   projects = "C:/Users/Kateri/Box/NSF Senegal",
#   p1 = "<projects>/Data Work/Output/Data Corrections"
# ))

file_path_hh <- file.path(proj$p1, "Complete_Baseline_Household_Roster.dta")
household_df <- read_dta(file_path_hh)

file_path_know <- file.path(proj$p1, "Complete_Baseline_Knowledge.dta")
knowledge_df <- read_dta(file_path_know)

file_path_health <- file.path(proj$p1, "Complete_Baseline_Health.dta")
health_df <- read_dta(file_path_health)

file_path_agri <- file.path(proj$p1, "Complete_Baseline_Agriculture.dta")
agriculture_df <- read_dta(file_path_agri)

file_path_prod <- file.path(proj$p1, "Complete_Baseline_Production.dta")
production_df <- read_dta(file_path_prod)

file_path_cop <- file.path(proj$p1, "Complete_Baseline_Lean_Season.dta")
coping_df <- read_dta(file_path_cop)

file_path_income <- file.path(proj$p1, "Complete_Baseline_Income.dta")
income_df <- read_dta(file_path_income)

file_path_standard <- file.path(proj$p1, "Complete_Baseline_Standard_Of_Living.dta")
standard_df <- read_dta(file_path_standard)

file_path_beliefs <- file.path(proj$p1, "Complete_Baseline_Beliefs.dta")
beliefs_df <- read_dta(file_path_beliefs)

file_path_game <- file.path(proj$p1, "Complete_Baseline_Public_Goods_Game.dta")
donation_df <- read_dta(file_path_game)

file_path_enumerator <- file.path(proj$p1, "Complete_Baseline_Enumerator_Observations.dta")
enumerator_df <- read_dta(file_path_enumerator)

file_path_community <- file.path(proj$p1, "Complete_Baseline_Community.dta")
community_df <- read_dta(file_path_community)



#print(head(baseline_data, 10))

#baseline_data <- baseline_data %>%
 # mutate(hh_age_resp = if_else(hhid == "023B09", 50, hh_age_resp))

```


##merge necessary DFs

```{r}


# Define possible paths
path1 <- "C:\\Users\\kateri\\Box\\NSF Senegal\\Data Management\\_PartnerData\\Child infection dataframe\\Clean Data"
path2 <- "C:\\Users\\km978\\Box\\NSF Senegal\\Data Management\\Output\\Data Analysis\\Balance_Tables"

# set the working directory
if (dir.exists(path1)) {
  setwd(path1)
} else if (dir.exists(path2)) {
  setwd(path2)
}


# Merge all datasets by 'hhid'
merged_df <- household_df

merged_df <- merge(merged_df, health_df, by = "hhid", all = TRUE)
merged_df <- merge(merged_df, agriculture_df, by = "hhid", all = TRUE)
merged_df <- merge(merged_df, production_df, by = "hhid", all = TRUE)
merged_df <- merge(merged_df, income_df, by = "hhid", all = TRUE)
merged_df <- merge(merged_df, standard_df, by = "hhid", all = TRUE)
merged_df <- merge(merged_df, donation_df, by = "hhid", all = TRUE)
merged_df <- merge(merged_df, enumerator_df, by = "hhid", all = TRUE)

# View the merged dataframe
head(merged_df)

tables_df <- merged_df %>%
select(hhid, hhid_village, starts_with("hh_gender"), starts_with("hh_age"), starts_with("hh_education_skills"), starts_with("hh_education_level"), starts_with("hh_education_year_achieve"), starts_with("hh_number"), starts_with("hh_03"), starts_with("hh_10"), starts_with("hh_11"), starts_with("hh_12"), starts_with("hh_13"), starts_with("hh_14"), starts_with("hh_15"), starts_with("hh_16"), starts_with("hh_29"), starts_with("hh_16"), starts_with("health_5_2"), starts_with("health_5_3"), starts_with("health_5_5"), starts_with("health_5_6"), starts_with("health_5_7"), starts_with("agri_6_15"), starts_with("species"), starts_with("agri_income_05"), starts_with("living_01"), starts_with("living_03"), starts_with("living_04"),starts_with("living_05"),starts_with("amount_02"), starts_with("amount_05"), starts_with("face_04"),starts_with("face_13"),starts_with("enum_03"),starts_with("enum_04"),starts_with("enum_05") 
       )

#to remove 
#hh_12_r  hh_12name_4_7 hh_12index_4_5 "hh_education_level_o_31" hh_11_o_12 hh_education_skills_0_52


tables_df <- tables_df  %>%
select(-starts_with("hh_12_r"), -starts_with("hh_12name_"), -starts_with("hh_12_calc_"), -starts_with("hh_12index_"), -starts_with("hh_education_level_o_"), -starts_with("hh_11_o_"), -starts_with("hh_education_skills_0_"),  -starts_with("hh_15_o_"), -starts_with("hh_gender_res"), -starts_with("hh_29_o")  
)



# Drop columns with numbered suffixes (1 to 55) for specific patterns
cols_to_drop <- unlist(lapply(1:55, function(i) {
  c(paste0("hh_education_skills_", i),
    paste0("hh_12_", i),
    paste0("health_5_3_", i))
}))

# Drop other specific patterns
additional_cols_to_drop <- c(
  grep("^hh_12_o", names(tables_df), value = TRUE),
  grep("^hh_12_a", names(tables_df), value = TRUE),
  grep("^hh_13_s", names(tables_df), value = TRUE),
  grep("^hh_13_o", names(tables_df), value = TRUE),
  grep("^hh_20index", names(tables_df), value = TRUE),
  grep("^hh_20index", names(tables_df), value = TRUE),
  grep("^hh_20name_1_2", names(tables_df), value = TRUE),
  "living_01_o", "living_03_o", "living_04_o", "living_05_o",
  "enum_03_o", "enum_04_o", "enum_05_o", "species_o"
)

# Combine all columns to drop
all_cols_to_drop <- unique(c(cols_to_drop, additional_cols_to_drop))

# Subset the tables_df by removing the columns
tables_df <- tables_df[ , !(names(tables_df) %in% all_cols_to_drop)]

tables_df <- tables_df %>%
  mutate(across(starts_with("hh_education_skills"), as.numeric),
         across(starts_with("hh_12_"), as.numeric),
          across(starts_with("health_5_3"), as.numeric)
          # across(starts_with("hh_12_"), as.numeric),
          # across(starts_with("hh_12_"), as.numeric),
          # 
                  )


# Generate a list of variable names
for (i in 1:7) {
  for (j in 1:55) {
    # Construct old and new variable names
    oldname <- paste0("hh_13_", j, "_", i)
    newname <- paste0("hh_13_", i, "_", j)
    
    # Rename columns if the old variable exists
    if (oldname %in% colnames(tables_df)) {
      colnames(tables_df)[colnames(tables_df) == oldname] <- newname
    }
  }
}


# View the updated dataset
colnames(tables_df)

view(tables_df)





#write_dta(tables_df, "balance_tables_data.dta")


# head(tables_df)
#view(tables_df)
# names(tables_df)
# sapply(tables_df, class)
```


##switch from wide to long 


```{r}


# Reshape data from wide to long
tables_df_long <- tables_df %>%
  pivot_longer(
    cols = c(
      "hh_gender_", "hh_age_", 
      "hh_education_skills_1_", "hh_education_skills_2_", "hh_education_skills_3_", 
      "hh_education_skills_4_", "hh_education_skills_5_", 
      "health_5_3_1_", "health_5_3_2_", "health_5_3_3_", "health_5_3_4_", "health_5_3_5_", 
      "health_5_3_6_", "health_5_3_7_", "health_5_3_8_", "health_5_3_9_", "health_5_3_10_", 
      "health_5_3_11_", "health_5_3_12_", "health_5_3_13_", "health_5_3_14_", "health_5_3_15_", 
      "health_5_3_99_", 
      "hh_education_level_", "hh_education_year_achieve_", 
      "hh_number_", "hh_03_", "hh_10_", "hh_11_", 
      "hh_12_1_", "hh_12_2_", "hh_12_3_", "hh_12_4_", "hh_12_5_", "hh_12_6_", 
      "hh_12_7_", "hh_12_8_", 
      "hh_13_1_", "hh_13_2_", "hh_13_3_", "hh_13_4_", "hh_13_5_", "hh_13_6_", "hh_13_7_", 
      "hh_14_", "hh_15_", "hh_16_", "hh_29_", 
      "health_5_2_", "health_5_3_", "health_5_5_", "health_5_6_", "health_5_7_"
    ),  # List of all columns to reshape
    names_to = "id",        # Column to store the names of reshaped variables
    values_to = "value"     # Column to store values
  )

# View the reshaped data
view(tables_df_long)

 
# 
# tables_df_long <- tables_df %>%
#   pivot_longer(
#     cols = starts_with("hh_") | starts_with("health_5_"),  # Use starts_with() for matching
#     names_to = "variable",
#     values_to = "value"
#   )
# 
# 
# tables_df
# 
# tables_df_long <- tables_df %>%
#   pivot_longer(
#     cols = starts_with("hh_age_"), # Use starts_with() for matching
#     names_to = "variable",
#     values_to = "value"
#   )
# 
# view(tables_df_long)
# 
# head(tables_df_long)
```



filter by treatment group

```{r}

view(trained_data)
# Adding indicator variables for household training categories
trained_data <- trained_data %>%
  mutate(
    # Extract the two middle characters (e.g., 2A) from hhid
    group = str_sub(hhid, 3, 4),
    
    # Add indicator variables based on the group value
    control = if_else(group %in% c("0A", "0B"), 1, 0),
    public_health_trained = if_else(group %in% c("1A", "1B"), 1, 0),
    private_benefits_trained = if_else(group %in% c("2A", "2B"), 1, 0),
    public_and_private_trained = if_else(group %in% c("3A", "3B"), 1, 0)
  ) %>%
  # Drop the 'group' column if it's not needed
  select(-group)




```






