project:
  type: website

website:
  title: "My Team's Project Dashboard"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: Project A
        menu:
          - text: Balance Table
            file: projects/projectA/balance-table.qmd
          - text: Ecological Analysis
            file: projects/projectA/ecological-analysis.qmd
format:
  html:
    theme: cosmo
    toc: true