---
title: "Treatment_Arms"
author: "Kateri Mouawad"
date: "2025-01-03"
output: html_document
---

#START HERE - load packages

```{r}

#remotes::install_github("kwb-r/kwb.utils")

#options(repos = c(
#  kwbr = 'https://kwb-r.r-universe.dev',
#  CRAN = 'https://cloud.r-project.org'))
  
# Download and install kwb.utils in R
#install.packages('kwb.utils')




# install.packages(officer)
# install.packages(r2rtf)
# install.packages(dplyr)
# install.packages(ggplot2)
# install.packages(kwb.utils)
# install.packages(haven)
# install.packages(data.table)
# install.packages(rtf)
# install.packages(tidyverse)
# install.packages(estimatr)
# install.packages(broom)

library(officer)
library(r2rtf)
library(dplyr)
library(ggplot2)
library(kwb.utils)
library(haven)
library(data.table)
library(rtf)
library(tidyverse)
library(estimatr)
library(broom)

```

#Run paths

```{r}


# Define the file paths
proj_paths <- list(
  projects = "C:/Users/Kateri/Box/NSF Senegal",
  alternative_projects = "C:/Users/km978/Box/NSF Senegal"
)


# Check if the Kateri path exists and resolve the project path accordingly
if (file.exists(proj_paths$projects)) {
  proj <- kwb.utils::resolve(list(
    projects = proj_paths$projects,
    p1 = "<projects>/Data Management/Output/Data Corrections/Treatments"
  ))
} else {
  proj <- kwb.utils::resolve(list(
    projects = proj_paths$alternative_projects,
    p1 = "<projects>/Data Management/Output/Data Corrections/Treatments"
  ))
}


file_path_hh <- file.path(proj$p1, "Treated_variables_df.dta")
trained_data <- read_dta(file_path_hh)
view(trained_data)




```





#Create treatment arm variables

```{r}

#Village level co-variates
# Define possible paths
path1 <- "C:/Users/km978/Box/NSF Senegal/Data Management/Output/Data Corrections/Baseline"
path2 <- "C:/Users/km978/Box/NSF Senegal/Data Management/Output/Data Corrections/Baseline"


# set the working directory
if (dir.exists(path1)) {
  setwd(path1)
} else if (dir.exists(path2)) {
  setwd(path2)
}


# Adding indicator variables for household training categories
trained_data <- trained_data %>%
  mutate(
    # Extract the two middle characters (e.g., 2A) from hhid
    group = str_sub(hhid, 3, 4),
    
    # Add indicator variables based on the group value
    control = if_else(group %in% c("0A", "0B"), 1, 0),
    public_health_trained = if_else(group %in% c("1A", "1B"), 1, 0),
    private_benefits_trained = if_else(group %in% c("2A", "2B"), 1, 0),
    public_and_private_trained = if_else(group %in% c("3A", "3B"), 1, 0)
  ) %>%
  # Drop the 'group' column if it's not needed
  select(-group)


# View the updated dataframe
head(trained_data)

#view(trained_data)

#write.csv(trained_data, "trained_and_treatment_arms", row.names = TRUE)


```



#Summarize 

```{r}

# Define possible paths
path1 <- "C:/Users/km978/Downloads/SenegalGIT/Latex_Output/Treatment_Arms"
path2 <- "C:/Users/Kateri/Downloads/SenegalGIT/Latex_Output/Treatment_Arms"

# set the working directory
if (dir.exists(path1)) {
  setwd(path1)
} else if (dir.exists(path2)) {
  setwd(path2)
}



# Function to calculate summary statistics for a single vector (variable)
binary_func_l <- function(value) {

  # Calculate summary statistics for 0s and 1s
  binary_stats_l <- data.frame(
    N = round(sum(!is.na(value)), 2),
    Mean = round(mean(ifelse(value == -9, NA, value), na.rm = TRUE), 2),
    SD = round(sd(ifelse(value == -9, NA, value), na.rm = TRUE), 2),
    prop_na = round(sum(value == -9, na.rm = TRUE) / sum(!is.na(value)), 2)
  )
  
  return(binary_stats_l)
}

binary_summary_l <- function(baseline_data, prefixes) {
  # Loop over each prefix
  summaries_binary_l <- lapply(prefixes, function(prefix) {
    # Select the column that matches the prefix
    selected_data <- baseline_data %>%
      select(starts_with(prefix))
    
    # Pull the column values and pass to binary_func_l
    value <- selected_data[[1]]
    summary_stats <- binary_func_l(value)
    
    # Add the prefix (variable name) to the summary
    summary_stats$Variable <- prefix
    
          # Reorder columns so Variable_l is first
    summary_stats <- summary_stats %>%
      select(Variable, everything())
    
    return(summary_stats)
  })
  
  binary_sum_set_l <- bind_rows(summaries_binary_l)
  return(binary_sum_set_l)
}


treatment_prefixes <- c("control", "public_health_trained", "private_benefits_trained", "public_and_private_trained")
treat_output <- (binary_summary_l(trained_data, treatment_prefixes))


treat_output <- treat_output %>%
  mutate(Variable = recode(Variable,
    "control" = "Control",
    "public_health_trained" = "Public Benefits Treatment Arm",
    "private_benefits_trained" = "Private Benefits Treatment Arm",
    "public_and_private_trained" = "Public & Private Benefits Treatment Arm"
  ))

treat_output <- treat_output %>%
  select(-prop_na)

# Create the gt table
treat_output_gt <- gt(treat_output) %>%
  tab_header(
    title = "Treatment Arm Variables"
  )

gtsave(treat_output_gt, "treatment_arm_vars.tex")
treat_output_gt




```























