*** DISES Midline Data Checks - Household Survey***
*** File originally created By: Molly Doruska - Adapted by Kateri Mouawad & Alex Mills ***
*** Updates recorded in GitHub ***

*>>>>>>>>>>*===========================* READ ME *===========================*<<<<<<<<<<<*


			*1)	Go to the following file path:
					*Data Management\Output\Data Quality Checks\Midline
			*2)	Check for through each of the subfolders to verify which issues have been outputed 
			*3)	Update this script with any new .dta's by appending them, module by module 
			*4) After you apppend all of the issues by module, complete one final append by appending the module issues 
			*5) Export this spread sheet to the Issues folder located here:
				*\Data Management\External_Corrections\Issues for Justin and Amina\Midline\Issues
			

*==============================================================================
clear all
set mem 100m
set maxvar 30000
set matsize 11000
set more off

**************************************************
* SET FILE PATHS
**************************************************

* Set base Box path for each user
if "`c(username)'"=="socrm" global master "C:\Users\socrm\Box"
if "`c(username)'"=="kls329" global master "C:\Users\kls329\Box"
if "`c(username)'"=="km978" global master "C:\Users\km978\Box\NSF Senegal"
if "`c(username)'"=="Kateri" global master "C:\Users\Kateri\Box\NSF Senegal"
if "`c(username)'"=="admmi" global master "C:\Users\admmi\Box\NSF Senegal"



global village_observations "$master\Data Management\Output\Data Quality Checks\Midline\R2_Village_Observations"
global household_roster "$master\Data Management\Output\Data Quality Checks\Midline\R2_Household_Roster"
global knowledge "$master\Data Management\Output\Data Quality Checks\Midline\R2_Knowledge"
global health "$master\Data Management\Output\Data Quality Checks\Midline\R2_Health" 
global agriculture_inputs "$master\Data Management\Output\Data Quality Checks\Midline\R2_Agriculture_Inputs"
global agriculture_production "$master\Data Management\Output\Data Quality Checks\Midline\R2_Agriculture_Production"
global food_consumption "$master\Data Management\Output\Data Quality Checks\Midline\R2_Food_Consumption"
global income "$master\Data Management\Output\Data Quality Checks\Midline\R2_Income"
global standard_living "$master\Data Management\Output\Data Quality Checks\Midline\R2_Standard_Living"
global beliefs "$master\Data Management\Output\Data Quality Checks\Midline\R2_Beliefs" 
global enum_observations "$master\Data Management\Output\Data Quality Checks\Midline\R2_Enumerator_Observations"


************************* Final output file path **********************************


global issues "$master\Data Management\External_Corrections\Issues for Justin and Amina\Midline\Issues"


********************** COMBINE FILES INTO SECTION FILES **********************

*** Combine village observation files ***


************************* CHECK TO SEE WHAT WAS OUTPUT *****************

*** Combine household roster files ***
************************* CHECK TO SEE WHAT WAS OUTPUT *****************
use "$household_roster\Issue_Household_hh_age_1.dta", clear 

append using "$household_roster\Issue_hh_13_3_total_unreasonable.dta"
append using "$household_roster\Issue_hh_13_2_total_unreasonable.dta"
append using "$household_roster\Issue_hh_13_1_total_unreasonable.dta"
append using "$household_roster\Issue_hh_12_o_1.dta"
append using "$household_roster\Issue_Household_sum_less_than_hh_18_11.dta"
append using "$household_roster\Issue_Household_sum_less_than_hh_18_10.dta"
append using "$household_roster\Issue_Household_sum_less_than_hh_18_9.dta"
append using "$household_roster\Issue_Household_sum_less_than_hh_18_8.dta"
append using "$household_roster\Issue_Household_sum_less_than_hh_18_7.dta"
append using "$household_roster\Issue_Household_sum_less_than_hh_18_6.dta"
append using "$household_roster\Issue_Household_sum_less_than_hh_18_5.dta"
append using "$household_roster\Issue_Household_sum_less_than_hh_18_4.dta"
append using "$household_roster\Issue_Household_sum_less_than_hh_18_3.dta"
append using "$household_roster\Issue_Household_sum_less_than_hh_18_2.dta"
append using "$household_roster\Issue_Household_sum_less_than_hh_18_1.dta"
append using "$household_roster\Issue_Household_hh_education_level_13.dta"
append using "$household_roster\Issue_Household_hh_education_level_6.dta"
append using "$household_roster\Issue_Household_hh_education_level_5.dta"
append using "$household_roster\Issue_Household_hh_education_level_4.dta"
append using "$household_roster\Issue_Household_hh_education_level_2.dta"
append using "$household_roster\Issue_Household_hh_education_level_1.dta"
append using "$household_roster\Issue_Household_hh_age_28.dta"
append using "$household_roster\Issue_Household_hh_age_27.dta"
append using "$household_roster\Issue_Household_hh_age_26.dta"
append using "$household_roster\Issue_Household_hh_age_25.dta"
append using "$household_roster\Issue_Household_hh_age_24.dta"
append using "$household_roster\Issue_Household_hh_age_23.dta"
append using "$household_roster\Issue_Household_hh_age_22.dta"
append using "$household_roster\Issue_Household_hh_age_21.dta"
append using "$household_roster\Issue_Household_hh_age_20.dta"
append using "$household_roster\Issue_Household_hh_age_19.dta"
append using "$household_roster\Issue_Household_hh_age_18.dta"
append using "$household_roster\Issue_Household_hh_age_17.dta"
append using "$household_roster\Issue_Household_hh_age_16.dta"
append using "$household_roster\Issue_Household_hh_age_15.dta"
append using "$household_roster\Issue_Household_hh_age_14.dta"
append using "$household_roster\Issue_Household_hh_age_13.dta"
append using "$household_roster\Issue_Household_hh_age_12.dta"
append using "$household_roster\Issue_Household_hh_age_11.dta"
append using "$household_roster\Issue_Household_hh_age_10.dta"
append using "$household_roster\Issue_Household_hh_age_9.dta"
append using "$household_roster\Issue_Household_hh_age_8.dta"
append using "$household_roster\Issue_Household_hh_age_7.dta"
append using "$household_roster\Issue_Household_hh_age_6.dta"
append using "$household_roster\Issue_Household_hh_age_5.dta"
append using "$household_roster\Issue_Household_hh_age_4.dta"
append using "$household_roster\Issue_Household_hh_age_3.dta"
append using "$household_roster\Issue_Household_hh_age_2.dta"
append using "$household_roster\Issue_Household_hh_age_1.dta"
append using "$household_roster\Issue_Household_hh_10_28_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_10_27_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_10_26_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_10_25_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_10_24_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_10_23_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_10_22_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_10_21_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_10_20_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_10_19_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_10_18_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_10_17_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_10_16_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_10_15_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_10_14_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_10_13_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_10_12_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_10_11_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_10_10_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_10_9_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_10_8_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_10_7_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_10_6_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_10_5_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_10_4_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_10_3_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_10_2_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_10_1_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_28_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_27_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_26_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_25_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_24_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_23_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_22_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_21_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_20_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_19_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_18_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_17_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_16_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_15_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_14_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_13_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_12_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_11_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_10_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_9_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_8_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_7_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_6_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_5_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_4_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_3_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_2_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_09_1_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_28_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_27_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_26_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_25_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_24_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_23_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_22_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_21_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_20_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_19_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_18_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_17_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_16_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_15_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_14_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_13_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_12_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_11_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_10_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_9_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_8_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_7_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_6_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_5_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_4_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_3_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_2_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_08_1_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_03_28.dta"
append using "$household_roster\Issue_Household_hh_03_27.dta"
append using "$household_roster\Issue_Household_hh_03_26.dta"
append using "$household_roster\Issue_Household_hh_03_25.dta"
append using "$household_roster\Issue_Household_hh_03_24.dta"
append using "$household_roster\Issue_Household_hh_03_23.dta"
append using "$household_roster\Issue_Household_hh_03_22.dta"
append using "$household_roster\Issue_Household_hh_03_21.dta"
append using "$household_roster\Issue_Household_hh_03_20.dta"
append using "$household_roster\Issue_Household_hh_03_19.dta"
append using "$household_roster\Issue_Household_hh_03_18.dta"
append using "$household_roster\Issue_Household_hh_03_17.dta"
append using "$household_roster\Issue_Household_hh_03_16.dta"
append using "$household_roster\Issue_Household_hh_03_15.dta"
append using "$household_roster\Issue_Household_hh_03_14.dta"
append using "$household_roster\Issue_Household_hh_03_13.dta"
append using "$household_roster\Issue_Household_hh_03_12.dta"
append using "$household_roster\Issue_Household_hh_03_11.dta"
append using "$household_roster\Issue_Household_hh_03_10.dta"
append using "$household_roster\Issue_Household_hh_03_9.dta"
append using "$household_roster\Issue_Household_hh_03_8.dta"
append using "$household_roster\Issue_Household_hh_03_7.dta"
append using "$household_roster\Issue_Household_hh_03_6.dta"
append using "$household_roster\Issue_Household_hh_03_5.dta"
append using "$household_roster\Issue_Household_hh_03_4.dta"
append using "$household_roster\Issue_Household_hh_03_3.dta"
append using "$household_roster\Issue_Household_hh_03_2.dta"
append using "$household_roster\Issue_Household_hh_03_1.dta"
append using "$household_roster\Issue_Household_hh_02_28_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_02_27_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_02_26_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_02_25_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_02_24_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_02_23_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_02_22_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_02_21_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_02_20_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_02_19_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_02_18_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_02_17_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_02_16_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_02_15_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_02_14_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_02_13_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_02_12_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_02_11_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_02_10_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_02_9_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_02_8_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_02_7_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_02_6_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_02_5_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_02_4_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_02_3_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_02_2_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_02_1_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_28_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_27_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_26_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_25_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_24_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_23_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_22_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_21_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_20_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_19_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_18_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_17_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_16_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_15_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_14_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_13_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_12_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_11_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_10_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_9_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_8_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_7_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_6_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_5_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_4_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_3_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_2_unreasonable.dta"
append using "$household_roster\Issue_Household_hh_01_1_unreasonable.dta"
append using "$household_roster\Issue_hh_47_oth_28.dta"
append using "$household_roster\Issue_hh_47_oth_27.dta"
append using "$household_roster\Issue_hh_47_oth_26.dta"
append using "$household_roster\Issue_hh_47_oth_25.dta"
append using "$household_roster\Issue_hh_47_oth_24.dta"
append using "$household_roster\Issue_hh_47_oth_23.dta"
append using "$household_roster\Issue_hh_47_oth_22.dta"
append using "$household_roster\Issue_hh_47_oth_21.dta"
append using "$household_roster\Issue_hh_47_oth_20.dta"
append using "$household_roster\Issue_hh_47_oth_19.dta"
append using "$household_roster\Issue_hh_47_oth_18.dta"
append using "$household_roster\Issue_hh_47_oth_17.dta"
append using "$household_roster\Issue_hh_47_oth_16.dta"
append using "$household_roster\Issue_hh_47_oth_15.dta"
append using "$household_roster\Issue_hh_47_oth_14.dta"
append using "$household_roster\Issue_hh_47_oth_13.dta"
append using "$household_roster\Issue_hh_47_oth_12.dta"
append using "$household_roster\Issue_hh_47_oth_11.dta"
append using "$household_roster\Issue_hh_47_oth_10.dta"
append using "$household_roster\Issue_hh_47_oth_9.dta"
append using "$household_roster\Issue_hh_47_oth_8.dta"
append using "$household_roster\Issue_hh_47_oth_7.dta"
append using "$household_roster\Issue_hh_47_oth_6.dta"
append using "$household_roster\Issue_hh_47_oth_5.dta"
append using "$household_roster\Issue_hh_47_oth_4.dta"
append using "$household_roster\Issue_hh_47_oth_3.dta"
append using "$household_roster\Issue_hh_47_oth_2.dta"
append using "$household_roster\Issue_hh_47_oth_1.dta"
append using "$household_roster\Issue_hh_46_6.dta"
append using "$household_roster\Issue_hh_44_6.dta"
append using "$household_roster\Issue_hh_29_23.dta"
append using "$household_roster\Issue_hh_29_22.dta"
append using "$household_roster\Issue_hh_29_21.dta"
append using "$household_roster\Issue_hh_29_20.dta"
append using "$household_roster\Issue_hh_29_19.dta"
append using "$household_roster\Issue_hh_29_18.dta"
append using "$household_roster\Issue_hh_29_17.dta"
append using "$household_roster\Issue_hh_29_16.dta"
append using "$household_roster\Issue_hh_29_15.dta"
append using "$household_roster\Issue_hh_29_14.dta"
append using "$household_roster\Issue_hh_29_13.dta"
append using "$household_roster\Issue_hh_29_12.dta"
append using "$household_roster\Issue_hh_29_11.dta"
append using "$household_roster\Issue_hh_29_10.dta"
append using "$household_roster\Issue_hh_29_9.dta"
append using "$household_roster\Issue_hh_29_8.dta"
append using "$household_roster\Issue_hh_29_7.dta"
append using "$household_roster\Issue_hh_29_6.dta"
append using "$household_roster\Issue_hh_29_5.dta"
append using "$household_roster\Issue_hh_29_4.dta"
append using "$household_roster\Issue_hh_29_3.dta"
append using "$household_roster\Issue_hh_29_2.dta"
append using "$household_roster\Issue_hh_29_1.dta"
append using "$household_roster\Issue_hh_13_13_total_unreasonable.dta"
append using "$household_roster\Issue_hh_13_10_total_unreasonable.dta"
append using "$household_roster\Issue_hh_13_9_total_unreasonable.dta"
append using "$household_roster\Issue_hh_13_8_total_unreasonable.dta"
append using "$household_roster\Issue_hh_13_7_total_unreasonable.dta"
append using "$household_roster\Issue_hh_13_6_total_unreasonable.dta"
append using "$household_roster\Issue_hh_13_5_total_unreasonable.dta"
append using "$household_roster\Issue_hh_13_4_total_unreasonable.dta"



save "$household_roster\Roster_Issues.dta", replace 

*** Combine knowledge files ***
************************* CHECK TO SEE WHAT WAS OUTPUT *****************

*** Combine health files ***
************************* CHECK TO SEE WHAT WAS OUTPUT *****************
use "$health\Issue_Household_health_5_9_23.dta", clear 
append using "$health\Issue_Household_health_5_9_24.dta"
append using "$health\Issue_Household_health_5_9_25.dta"
append using "$health\Issue_Household_health_5_9_26.dta"
append using "$health\Issue_Household_health_5_9_27.dta"
append using "$health\Issue_Household_health_5_9_28.dta"
append using "$health\Issue_health_5_12_1.dta"
append using "$health\Issue_health_5_12_3.dta"
append using "$health\Issue_health_5_12_5.dta"
append using "$health\Issue_Household_health_5_2_1.dta"
append using "$health\Issue_Household_health_5_2_2.dta"
append using "$health\Issue_Household_health_5_2_3.dta"
append using "$health\Issue_Household_health_5_2_4.dta"
append using "$health\Issue_Household_health_5_2_5.dta"
append using "$health\Issue_Household_health_5_2_6.dta"
append using "$health\Issue_Household_health_5_2_7.dta"
append using "$health\Issue_Household_health_5_2_8.dta"
append using "$health\Issue_Household_health_5_2_9.dta"
append using "$health\Issue_Household_health_5_2_10.dta"
append using "$health\Issue_Household_health_5_2_11.dta"
append using "$health\Issue_Household_health_5_2_12.dta"
append using "$health\Issue_Household_health_5_2_13.dta"
append using "$health\Issue_Household_health_5_2_14.dta"
append using "$health\Issue_Household_health_5_2_15.dta"
append using "$health\Issue_Household_health_5_2_16.dta"
append using "$health\Issue_Household_health_5_2_17.dta"
append using "$health\Issue_Household_health_5_2_18.dta"
append using "$health\Issue_Household_health_5_2_19.dta"
append using "$health\Issue_Household_health_5_2_20.dta"
append using "$health\Issue_Household_health_5_2_21.dta"
append using "$health\Issue_Household_health_5_2_22.dta"
append using "$health\Issue_Household_health_5_2_23.dta"
append using "$health\Issue_Household_health_5_2_24.dta"
append using "$health\Issue_Household_health_5_2_25.dta"
append using "$health\Issue_Household_health_5_2_26.dta"
append using "$health\Issue_Household_health_5_2_27.dta"
append using "$health\Issue_Household_health_5_2_28.dta"
append using "$health\Issue_Household_health_5_5_1.dta"
append using "$health\Issue_Household_health_5_5_2.dta"
append using "$health\Issue_Household_health_5_5_3.dta"
append using "$health\Issue_Household_health_5_5_4.dta"
append using "$health\Issue_Household_health_5_5_5.dta"
append using "$health\Issue_Household_health_5_5_6.dta"
append using "$health\Issue_Household_health_5_5_7.dta"
append using "$health\Issue_Household_health_5_5_8.dta"
append using "$health\Issue_Household_health_5_5_9.dta"
append using "$health\Issue_Household_health_5_5_10.dta"
append using "$health\Issue_Household_health_5_5_11.dta"
append using "$health\Issue_Household_health_5_5_12.dta"
append using "$health\Issue_Household_health_5_5_13.dta"
append using "$health\Issue_Household_health_5_5_14.dta"
append using "$health\Issue_Household_health_5_5_15.dta"
append using "$health\Issue_Household_health_5_5_16.dta"
append using "$health\Issue_Household_health_5_5_17.dta"
append using "$health\Issue_Household_health_5_5_18.dta"
append using "$health\Issue_Household_health_5_5_19.dta"
append using "$health\Issue_Household_health_5_5_20.dta"
append using "$health\Issue_Household_health_5_5_21.dta"
append using "$health\Issue_Household_health_5_5_22.dta"
append using "$health\Issue_Household_health_5_5_23.dta"
append using "$health\Issue_Household_health_5_5_24.dta"
append using "$health\Issue_Household_health_5_5_25.dta"
append using "$health\Issue_Household_health_5_5_26.dta"
append using "$health\Issue_Household_health_5_5_27.dta"
append using "$health\Issue_Household_health_5_5_28.dta"
append using "$health\Issue_Household_health_5_6_1.dta"
append using "$health\Issue_Household_health_5_6_2.dta"
append using "$health\Issue_Household_health_5_6_3.dta"
append using "$health\Issue_Household_health_5_6_4.dta"
append using "$health\Issue_Household_health_5_6_5.dta"
append using "$health\Issue_Household_health_5_6_6.dta"
append using "$health\Issue_Household_health_5_6_7.dta"
append using "$health\Issue_Household_health_5_6_8.dta"
append using "$health\Issue_Household_health_5_6_9.dta"
append using "$health\Issue_Household_health_5_6_10.dta"
append using "$health\Issue_Household_health_5_6_11.dta"
append using "$health\Issue_Household_health_5_6_12.dta"
append using "$health\Issue_Household_health_5_6_13.dta"
append using "$health\Issue_Household_health_5_6_14.dta"
append using "$health\Issue_Household_health_5_6_15.dta"
append using "$health\Issue_Household_health_5_6_16.dta"
append using "$health\Issue_Household_health_5_6_17.dta"
append using "$health\Issue_Household_health_5_6_18.dta"
append using "$health\Issue_Household_health_5_6_19.dta"
append using "$health\Issue_Household_health_5_6_20.dta"
append using "$health\Issue_Household_health_5_6_21.dta"
append using "$health\Issue_Household_health_5_6_22.dta"
append using "$health\Issue_Household_health_5_6_23.dta"
append using "$health\Issue_Household_health_5_6_24.dta"
append using "$health\Issue_Household_health_5_6_25.dta"
append using "$health\Issue_Household_health_5_6_26.dta"
append using "$health\Issue_Household_health_5_6_27.dta"
append using "$health\Issue_Household_health_5_6_28.dta"
append using "$health\Issue_Household_health_5_7_1_1.dta"
append using "$health\Issue_Household_health_5_7_1_2.dta"
append using "$health\Issue_Household_health_5_7_1_3.dta"
append using "$health\Issue_Household_health_5_7_1_4.dta"
append using "$health\Issue_Household_health_5_7_1_5.dta"
append using "$health\Issue_Household_health_5_7_1_6.dta"
append using "$health\Issue_Household_health_5_7_1_7.dta"
append using "$health\Issue_Household_health_5_7_1_8.dta"
append using "$health\Issue_Household_health_5_7_1_9.dta"
append using "$health\Issue_Household_health_5_7_1_10.dta"
append using "$health\Issue_Household_health_5_7_1_11.dta"
append using "$health\Issue_Household_health_5_7_1_12.dta"
append using "$health\Issue_Household_health_5_7_1_13.dta"
append using "$health\Issue_Household_health_5_7_1_14.dta"
append using "$health\Issue_Household_health_5_7_1_15.dta"
append using "$health\Issue_Household_health_5_7_1_16.dta"
append using "$health\Issue_Household_health_5_7_1_17.dta"
append using "$health\Issue_Household_health_5_7_1_18.dta"
append using "$health\Issue_Household_health_5_7_1_19.dta"
append using "$health\Issue_Household_health_5_7_1_20.dta"
append using "$health\Issue_Household_health_5_7_1_21.dta"
append using "$health\Issue_Household_health_5_7_1_22.dta"
append using "$health\Issue_Household_health_5_7_1_23.dta"
append using "$health\Issue_Household_health_5_7_1_24.dta"
append using "$health\Issue_Household_health_5_7_1_25.dta"
append using "$health\Issue_Household_health_5_7_1_26.dta"
append using "$health\Issue_Household_health_5_7_1_27.dta"
append using "$health\Issue_Household_health_5_7_1_28.dta"
append using "$health\Issue_Household_health_5_8_1.dta"
append using "$health\Issue_Household_health_5_8_2.dta"
append using "$health\Issue_Household_health_5_8_3.dta"
append using "$health\Issue_Household_health_5_8_4.dta"
append using "$health\Issue_Household_health_5_8_5.dta"
append using "$health\Issue_Household_health_5_8_6.dta"
append using "$health\Issue_Household_health_5_8_7.dta"
append using "$health\Issue_Household_health_5_8_8.dta"
append using "$health\Issue_Household_health_5_8_9.dta"
append using "$health\Issue_Household_health_5_8_10.dta"
append using "$health\Issue_Household_health_5_8_11.dta"
append using "$health\Issue_Household_health_5_8_12.dta"
append using "$health\Issue_Household_health_5_8_13.dta"
append using "$health\Issue_Household_health_5_8_14.dta"
append using "$health\Issue_Household_health_5_8_15.dta"
append using "$health\Issue_Household_health_5_8_16.dta"
append using "$health\Issue_Household_health_5_8_17.dta"
append using "$health\Issue_Household_health_5_8_18.dta"
append using "$health\Issue_Household_health_5_8_19.dta"
append using "$health\Issue_Household_health_5_8_20.dta"
append using "$health\Issue_Household_health_5_8_21.dta"
append using "$health\Issue_Household_health_5_8_22.dta"
append using "$health\Issue_Household_health_5_8_23.dta"
append using "$health\Issue_Household_health_5_8_24.dta"
append using "$health\Issue_Household_health_5_8_25.dta"
append using "$health\Issue_Household_health_5_8_26.dta"
append using "$health\Issue_Household_health_5_8_27.dta"
append using "$health\Issue_Household_health_5_8_28.dta"
append using "$health\Issue_Household_health_5_9_1.dta"
append using "$health\Issue_Household_health_5_9_2.dta"
append using "$health\Issue_Household_health_5_9_3.dta"
append using "$health\Issue_Household_health_5_9_4.dta"
append using "$health\Issue_Household_health_5_9_5.dta"
append using "$health\Issue_Household_health_5_9_6.dta"
append using "$health\Issue_Household_health_5_9_7.dta"
append using "$health\Issue_Household_health_5_9_8.dta"
append using "$health\Issue_Household_health_5_9_9.dta"
append using "$health\Issue_Household_health_5_9_10.dta"
append using "$health\Issue_Household_health_5_9_11.dta"
append using "$health\Issue_Household_health_5_9_12.dta"
append using "$health\Issue_Household_health_5_9_13.dta"
append using "$health\Issue_Household_health_5_9_14.dta"
append using "$health\Issue_Household_health_5_9_15.dta"
append using "$health\Issue_Household_health_5_9_16.dta"
append using "$health\Issue_Household_health_5_9_17.dta"
append using "$health\Issue_Household_health_5_9_18.dta"
append using "$health\Issue_Household_health_5_9_19.dta"
append using "$health\Issue_Household_health_5_9_20.dta"
append using "$health\Issue_Household_health_5_9_21.dta"
append using "$health\Issue_Household_health_5_9_22.dta"


save "$health\Health_Issues.dta", replace 

*** Combine agriculture inputs files *** 
************************* CHECK TO SEE WHAT WAS OUTPUT *****************
use "$agriculture_inputs\Issue_agri_6_41_a_code_5_missing.dta", clear 
append using "$agriculture_inputs\Issue_agriculture_agri_6_6.dta"
append using "$agriculture_inputs\Issue_agri_6_5.dta"
append using "$agriculture_inputs\Issue_agri_6_28_1_missing.dta"
append using "$agriculture_inputs\Issue_agri_6_28_2_missing.dta"
append using "$agriculture_inputs\Issue_agri_6_28_3_missing.dta"
append using "$agriculture_inputs\Issue_agri_6_28_4_missing.dta"
append using "$agriculture_inputs\Issue_agri_6_38_a_code_1_missing.dta"
append using "$agriculture_inputs\Issue_agri_6_38_a_code_2_missing.dta"
append using "$agriculture_inputs\Issue_agri_6_39_a_1_unreasonable.dta"
append using "$agriculture_inputs\Issue_agri_6_39_a_2_unreasonable.dta"
append using "$agriculture_inputs\Issue_agri_6_39_a_code_1_missing.dta"
append using "$agriculture_inputs\Issue_agri_6_39_a_code_2_missing.dta"
append using "$agriculture_inputs\Issue_agri_6_39_a_code_3_missing.dta"
append using "$agriculture_inputs\Issue_agri_6_39_a_code_4_missing.dta"
append using "$agriculture_inputs\Issue_agri_6_40_a_1_unreasonable.dta"
append using "$agriculture_inputs\Issue_agri_6_40_a_code_1_missing.dta"
append using "$agriculture_inputs\Issue_agri_6_40_a_code_2_missing.dta"
append using "$agriculture_inputs\Issue_agri_6_40_a_code_3_missing.dta"
append using "$agriculture_inputs\Issue_agri_6_41_a_code_1_missing.dta"
append using "$agriculture_inputs\Issue_agri_6_41_a_code_2_missing.dta"
append using "$agriculture_inputs\Issue_agri_6_41_a_code_3_missing.dta"
append using "$agriculture_inputs\Issue_agri_6_41_a_code_4_missing.dta"


save "$agriculture_inputs\Ag_Inputs_Issues.dta", replace 

*** Combine agriculture produciton files *** 
************************* CHECK TO SEE WHAT WAS OUTPUT *****************
use "$agriculture_production\Issue_legumineuses_05_1_unreasonable.dta", clear 
append using "$agriculture_production\Issue_legumineuses_05_2_unreasonable.dta"
append using "$agriculture_production\Issue_legumineuses_05_3_unreasonable.dta"
append using "$agriculture_production\Issue_legumineuses_05_4_unreasonable.dta"
append using "$agriculture_production\Issue_legumineuses_05_5_unreasonable.dta"
append using "$agriculture_production\Issue_o_culture_01_unreasonable.dta"
append using "$agriculture_production\Issue_o_culture_05_unreasonable.dta"
append using "$agriculture_production\Issue_cereals_01_1_unreasonable.dta"
append using "$agriculture_production\Issue_cereals_01_3_unreasonable.dta"
append using "$agriculture_production\Issue_cereals_02_1_unreasonable.dta"
append using "$agriculture_production\Issue_cereals_03_1_unreasonable.dta"
append using "$agriculture_production\Issue_cereals_03_3_unreasonable.dta"
append using "$agriculture_production\Issue_cereals_04_1_unreasonable.dta"
append using "$agriculture_production\Issue_cereals_05_1_unreasonable.dta"
append using "$agriculture_production\Issue_cereals_05_6_unreasonable.dta"
append using "$agriculture_production\Issue_farines_02_2_unreasonable.dta"
append using "$agriculture_production\Issue_farines_05_2_unreasonable.dta"
append using "$agriculture_production\Issue_legumes_01_1_unreasonable.dta"
append using "$agriculture_production\Issue_legumes_01_3_unreasonable.dta"
append using "$agriculture_production\Issue_legumes_02_1_unreasonable.dta"
append using "$agriculture_production\Issue_legumes_02_3_unreasonable.dta"
append using "$agriculture_production\Issue_legumes_02_6_unreasonable.dta"
append using "$agriculture_production\Issue_legumes_04_1_unreasonable.dta"
append using "$agriculture_production\Issue_legumes_05_1_unreasonable.dta"
append using "$agriculture_production\Issue_legumes_05_3_unreasonable.dta"
append using "$agriculture_production\Issue_legumes_05_6_unreasonable.dta"
append using "$agriculture_production\Issue_legumineuses_01_5_unreasonable.dta"


save "$agriculture_production\Ag_Production_Issues.dta", replace 

*** Combine food consumption issue files *** 
************************* CHECK TO SEE WHAT DATA WAS OUTPUT *****************

*** Combine income issue files *** 
************************* CHECK TO SEE WHAT DATA WAS OUTPUT *****************
use "$income\Issue_agri_income_01_missing.dta", clear 
append using "$income\Issue_agri_income_03_unreasonable.dta"
append using "$income\Issue_agri_income_05_unreasonable.dta"
append using "$income\Issue_agri_income_06_unreasonable.dta"
append using "$income\Issue_agri_income_07_2_unreasonable.dta"
append using "$income\Issue_agri_income_07_o_unreasonable.dta"
append using "$income\Issue_agri_income_08_2_unreasonable.dta"
append using "$income\Issue_agri_income_08_3_unreasonable.dta"
append using "$income\Issue_agri_income_08_o_unreasonable.dta"
append using "$income\Issue_agri_income_11_1_unreasonable.dta"
append using "$income\Issue_agri_income_11_2_unreasonable.dta"
append using "$income\Issue_agri_income_12_2_unreasonable.dta"
append using "$income\Issue_agri_income_15_missing.dta"
append using "$income\Issue_agri_income_23_1_unreasonable.dta"
append using "$income\Issue_agri_income_29_unreasonable.dta"
append using "$income\Issue_agri_income_33_unreasonable.dta"
append using "$income\Issue_agri_income_45_2.dta"
append using "$income\Issue_animals_sales_o.dta"
append using "$income\Issue_expenses_goods_t.dta"

save "$income\Income_Issues.dta", replace 

*** Combine standard of living issue files *** 
************************* CHECK TO SEE WHAT WAS OUTPUT *****************


*** Combine enumerator observation issue files *** 
************************* CHECK TO SEE WHAT OUTPUT *****************
use "$enum_observations\Issue_enum_03.dta", clear 
append using "$enum_observations\Issue_enum_04.dta"
save "$enum_observations\Enumerator_Issues.dta", replace 


************** COMBINE SECTION FILES INTO ONE HOUSEHOLD ISSUES FILE *************

*** NOT ALL FILES EXIST YET *** 

use "$household_roster\Roster_Issues.dta", replace
*append using "$knowledge\Knoweldge_Issues.dta"
append using "$health\Health_Issues.dta"
append using "$agriculture_inputs\Ag_Inputs_Issues.dta"
append using "$agriculture_production\Ag_Production_Issues.dta"
*append using "$food_consumption\Food_Consumption_Issues.dta"
append using "$income\Income_Issues.dta"
*append using "$standard_living\Standard_of_Living_Issues.dta"
append using "$enum_observations\Enumerator_Issues.dta"

*** export combined household checks data file *** 
export excel using "$issues\Household_Data_Issues_24Jan2025.xlsx", firstrow(variables) replace 



