---
title: "Parasitological_Predictive_Analysis"
author: "Kateri Mouawad"
date: "2025-02-21"
output: html_document
---

#BEGIN HERE - load packages

```{r}

library(gt)
library(vcd)
library(r2rtf)
library(dplyr)
library(kwb.utils)
library(haven)
library(data.table)
library(rtf)
library(tidyverse)
library(estimatr)
library(stats)
library(stargazer)
library(pscl)
library(sandwich)
library(caret)
library(xtable)
library(languageserver)

```

## Define paths and load data 
```{r}
# Define the file paths
proj_paths <- list(
  projects = "C:/Users/Kateri/Box/NSF Senegal",
  alternative_projects = "C:/Users/km978/Box/NSF Senegal"
)

# Check if the Kateri path exists and resolve the project path accordingly
if (file.exists(proj_paths$projects)) {
  proj <- kwb.utils::resolve(list(
    projects = proj_paths$projects,
    p1 = "<projects>/Data_Management/Output/Data_Analysis/Parasitological_Analysis_Data/Analysis_Data"
  ))
} else {
  proj <- kwb.utils::resolve(list(
    projects = proj_paths$alternative_projects,
    p1 = "<projects>/Data_Management/Output/Data_Analysis/Parasitological_Analysis_Data/Analysis_Data"
  ))
}

file_path_infection_df <- file.path(proj$p1, "child_infection_dataframe_analysis.dta")
infection_df <- read_dta(file_path_infection_df)

infection_df

```


# compute summary stats 



































